export interface Indicator {
  id: string;
  name: string;
  description: string;
  source: string;
  useCase: string;
  category: 'macro' | 'meso' | 'micro';
  subcategory: string;
}

export const INDICATORS = {
  macro: {
    economy: [
      {
        id: 'gdp',
        name: 'GDP增速',
        description: '国家经济总量增长率，通常按年度或季度发布',
        source: '国家统计局',
        useCase: '判断经济周期阶段；GDP高增长期通常对应股市上升期',
        category: 'macro',
        subcategory: '宏观经济',
      },
      {
        id: 'cpi',
        name: 'CPI（消费者物价指数）',
        description: '衡量通货膨胀水平；超过3%视为高通胀',
        source: '国家统计局',
        useCase: '高通胀推高企业成本，压低利润；央行可能加息，打压股市',
        category: 'macro',
        subcategory: '宏观经济',
      },
      {
        id: 'ppi',
        name: 'PPI（生产者物价指数）',
        description: '上游生产端的价格变化，领先于CPI',
        source: '国家统计局',
        useCase: 'PPI上升→企业成本压力→利润下滑；反之亦然',
        category: 'macro',
        subcategory: '宏观经济',
      },
      {
        id: 'pmi',
        name: 'PMI（采购经理指数）',
        description: '制造业景气度的先行指标；50为荣枯线',
        source: '国家统计局/财新',
        useCase: 'PMI>50表示经济扩张，<50表示收缩；每月发布，实时性强',
        category: 'macro',
        subcategory: '宏观经济',
      },
      {
        id: 'unemployment',
        name: '失业率',
        description: '劳动力市场的就业状况',
        source: '国家统计局',
        useCase: '失业率上升→消费下降→企业盈利受压',
        category: 'macro',
        subcategory: '宏观经济',
      },
    ],
    liquidity: [
      {
        id: 'm2',
        name: 'M2货币供应量',
        description: '广义货币供应量，包括现金、活期存款等',
        source: '央行',
        useCase: 'M2增速>GDP增速表示流动性宽松，利好股市',
        category: 'macro',
        subcategory: '流动性与货币政策',
      },
      {
        id: 'socialfinance',
        name: '社融数据（社会融资规模）',
        description: '实体经济获得的融资总额',
        source: '央行',
        useCase: '社融增速下降→信用收缩→股市承压',
        category: 'macro',
        subcategory: '流动性与货币政策',
      },
      {
        id: 'lpr',
        name: 'LPR（贷款市场报价利率）',
        description: '商业银行新增贷款的参考利率',
        source: '央行',
        useCase: 'LPR下降→融资成本降低→企业和消费者更愿意借贷',
        category: 'macro',
        subcategory: '流动性与货币政策',
      },
      {
        id: 'bondyield',
        name: '国债收益率',
        description: '长期国债的收益率，反映无风险利率',
        source: '交易所',
        useCase: '国债收益率下降→股票相对吸引力上升；反之亦然',
        category: 'macro',
        subcategory: '流动性与货币政策',
      },
      {
        id: 'dr',
        name: '银行间流动性（DR001/DR007）',
        description: '银行间短期借贷利率',
        source: '交易所',
        useCase: '利率走高→流动性紧张→股市可能下跌',
        category: 'macro',
        subcategory: '流动性与货币政策',
      },
    ],
    policy: [
      {
        id: 'fiscal',
        name: '财政政策取向',
        description: '政府支出、减税等政策信号',
        source: '国务院/财政部',
        useCase: '积极财政政策（增支出）→刺激经济→利好股市',
        category: 'macro',
        subcategory: '政策与预期',
      },
      {
        id: 'industry',
        name: '产业政策',
        description: '政府对特定行业的扶持或限制',
        source: '各部委公告',
        useCase: '新能源补贴→光伏、新能源车板块上升',
        category: 'macro',
        subcategory: '政策与预期',
      },
      {
        id: 'exchange',
        name: '汇率（人民币对美元）',
        description: '人民币升贬值趋势',
        source: '央行',
        useCase: '人民币贬值→外资流出（北向资金减少）→股市承压',
        category: 'macro',
        subcategory: '政策与预期',
      },
      {
        id: 'northbound',
        name: '北向资金净流入',
        description: '外资通过沪深港通的净买入额',
        source: '交易所',
        useCase: '北向资金持续净流入→外资看好中国市场',
        category: 'macro',
        subcategory: '政策与预期',
      },
    ],
    valuation: [
      {
        id: 'pe300',
        name: '沪深300 PE（市盈率）',
        description: '主要蓝筹股的平均市盈率',
        source: '交易所',
        useCase: 'PE分位点<30%→低估；>70%→高估',
        category: 'macro',
        subcategory: '市场估值与情绪',
      },
      {
        id: 'allpe',
        name: '全A PE/PB',
        description: '全市场股票的平均市盈率和市净率',
        source: '交易所',
        useCase: '衡量整体市场估值水平',
        category: 'macro',
        subcategory: '市场估值与情绪',
      },
      {
        id: 'stockbond',
        name: '股债收益率差',
        description: '股票收益率与国债收益率的差值',
        source: '交易所',
        useCase: '差值过小→股票吸引力下降',
        category: 'macro',
        subcategory: '市场估值与情绪',
      },
      {
        id: 'margin',
        name: '融资余额',
        description: '投资者通过融资融券的未平仓头寸',
        source: '交易所',
        useCase: '融资余额高→市场情绪亢奋；快速下降→风险信号',
        category: 'macro',
        subcategory: '市场估值与情绪',
      },
      {
        id: 'marginratio',
        name: '两融余额占流通市值比',
        description: '融资融券与流通市值的比例',
        source: '交易所',
        useCase: '比例过高→市场杠杆过高，风险大',
        category: 'macro',
        subcategory: '市场估值与情绪',
      },
    ],
  },
  meso: {
    sentiment: [
      {
        id: 'profit_growth',
        name: '行业利润增速',
        description: '行业上市公司的合计净利润同比增长率',
        source: '交易所/研究机构',
        useCase: '利润增速>GDP增速→行业景气向好',
        category: 'meso',
        subcategory: '行业景气度',
      },
      {
        id: 'capacity',
        name: '产能利用率',
        description: '行业实际产能与总产能的比例',
        source: '行业协会/统计部门',
        useCase: '产能利用率>80%→产能紧张，价格上升',
        category: 'meso',
        subcategory: '行业景气度',
      },
      {
        id: 'inventory',
        name: '库存周期',
        description: '企业库存从积累到消化的周期',
        source: '行业数据',
        useCase: '库存低位→补库存需求强→行业景气上升',
        category: 'meso',
        subcategory: '行业景气度',
      },
      {
        id: 'order',
        name: '订单/出货量',
        description: '行业新增订单和出货量的变化',
        source: '行业协会',
        useCase: '订单增长→3-6个月后收入增长',
        category: 'meso',
        subcategory: '行业景气度',
      },
      {
        id: 'revenue_growth',
        name: '行业营收增速',
        description: '行业上市公司的合计营业收入同比增长率',
        source: '交易所/研究机构',
        useCase: '直观反映行业需求强度',
        category: 'meso',
        subcategory: '行业景气度',
      },
    ],
    valuation: [
      {
        id: 'industry_pe',
        name: '行业PE分位点',
        description: '行业平均PE相对于历史的位置',
        source: '交易所/研究机构',
        useCase: '<30%分位→低估；>70%分位→高估',
        category: 'meso',
        subcategory: '板块估值',
      },
      {
        id: 'industry_pb',
        name: '行业PB分位点',
        description: '行业平均PB相对于历史的位置',
        source: '交易所/研究机构',
        useCase: '结合PE判断估值水平',
        category: 'meso',
        subcategory: '板块估值',
      },
      {
        id: 'industry_peg',
        name: '行业PEG',
        description: '行业PE与增长率的比值',
        source: '研究机构',
        useCase: 'PEG<1→相对便宜；>2→相对昂贵',
        category: 'meso',
        subcategory: '板块估值',
      },
      {
        id: 'industry_dividend',
        name: '行业股债收益率差',
        description: '行业平均股息率与国债收益率的差值',
        source: '交易所',
        useCase: '差值过小→股票吸引力下降',
        category: 'meso',
        subcategory: '板块估值',
      },
    ],
    fund: [
      {
        id: 'fund_inflow',
        name: '行业资金净流入',
        description: '主动买入与卖出的差值',
        source: '交易所/软件',
        useCase: '持续净流入→机构看好；净流出→警惕',
        category: 'meso',
        subcategory: '资金与情绪',
      },
      {
        id: 'volume_ratio',
        name: '行业成交额占比',
        description: '行业成交额占全市场的比例',
        source: '交易所',
        useCase: '占比上升→热度提升；占比下降→热度下降',
        category: 'meso',
        subcategory: '资金与情绪',
      },
      {
        id: 'turnover',
        name: '行业换手率',
        description: '行业股票交易量与流通股本的比例',
        source: '交易所',
        useCase: '换手率过高→短期炒作；过低→缺乏关注',
        category: 'meso',
        subcategory: '资金与情绪',
      },
      {
        id: 'fund_holding',
        name: '公募基金持仓比例',
        description: '公募基金对该行业的配置比例',
        source: '基金业协会',
        useCase: '持仓比例上升→机构看好；下降→减仓信号',
        category: 'meso',
        subcategory: '资金与情绪',
      },
      {
        id: 'margin_industry',
        name: '融资余额占行业流通市值比',
        description: '行业融资融券与流通市值的比例',
        source: '交易所',
        useCase: '比例过高→杠杆过高，风险大',
        category: 'meso',
        subcategory: '资金与情绪',
      },
    ],
    catalyst: [
      {
        id: 'policy_support',
        name: '政策扶持力度',
        description: '政府对行业的补贴、税收优惠等',
        source: '政府部门',
        useCase: '新能源补贴增加→新能源板块上升',
        category: 'meso',
        subcategory: '外部催化',
      },
      {
        id: 'commodity',
        name: '国际大宗商品价格',
        description: '石油、铁矿石、铜等价格',
        source: '国际交易所',
        useCase: '油价上升→能源股上升；铁矿石价格上升→钢铁股上升',
        category: 'meso',
        subcategory: '外部催化',
      },
      {
        id: 'exchange_rate',
        name: '汇率变化',
        description: '人民币升贬值对出口行业的影响',
        source: '央行',
        useCase: '人民币贬值→出口企业竞争力上升',
        category: 'meso',
        subcategory: '外部催化',
      },
      {
        id: 'trade',
        name: '国际贸易形势',
        description: '关税、贸易协议等',
        source: '国际新闻',
        useCase: '贸易摩擦→出口行业承压',
        category: 'meso',
        subcategory: '外部催化',
      },
    ],
  },
  micro: {
    fundamental: [
      {
        id: 'roe',
        name: 'ROE（净资产收益率）',
        description: '净利润与净资产的比值，衡量企业盈利能力',
        source: '财务报表',
        useCase: 'ROE>15%→优秀；<5%→较差',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'roic',
        name: 'ROIC（投入资本回报率）',
        description: '企业投入资本的回报率',
        source: '财务报表',
        useCase: 'ROIC>10%→优秀；反映企业竞争力',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'revenue_growth_stock',
        name: '营收增长率',
        description: '营业收入同比增长百分比',
        source: '财务报表',
        useCase: '增长率>20%→高成长；<5%→成熟或衰退',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'profit_growth_stock',
        name: '净利润增长率',
        description: '净利润同比增长百分比',
        source: '财务报表',
        useCase: '反映企业盈利增长速度',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'gross_margin',
        name: '毛利率',
        description: '毛利与营收的比值',
        source: '财务报表',
        useCase: '毛利率高→产品竞争力强；低→行业竞争激烈',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'net_margin',
        name: '净利率',
        description: '净利润与营收的比值',
        source: '财务报表',
        useCase: '净利率高→成本控制好；低→费用负担重',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'ocf',
        name: '经营性现金流',
        description: '企业经营活动产生的现金流',
        source: '财务报表',
        useCase: '现金流>净利润→利润质量好；反之→风险信号',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
      {
        id: 'fcf',
        name: '自由现金流',
        description: '经营性现金流减去资本支出',
        source: '财务报表',
        useCase: '正数→企业有分红能力；负数→需要融资',
        category: 'micro',
        subcategory: '基本面（财务）',
      },
    ],
    valuation_stock: [
      {
        id: 'pe_stock',
        name: 'PE（市盈率）',
        description: '股票价格与每股收益的比值',
        source: '交易所',
        useCase: 'PE低→便宜；PE高→昂贵。需结合增长率判断',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'dynamic_pe',
        name: '动态PE',
        description: '基于预期未来12个月收益的PE',
        source: '研究机构',
        useCase: '比静态PE更前瞻',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'pb_stock',
        name: 'PB（市净率）',
        description: '股票价格与每股净资产的比值',
        source: '交易所',
        useCase: 'PB<1→破净；PB>3→高估。适用于资产密集型企业',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'ps_stock',
        name: 'PS（市销率）',
        description: '股票价格与每股营收的比值',
        source: '交易所',
        useCase: '适用于未盈利或低利润企业；PS低→便宜',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'peg_stock',
        name: 'PEG（PEG比率）',
        description: 'PE与增长率的比值',
        source: '研究机构',
        useCase: 'PEG<1→相对便宜；>2→相对昂贵',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'ev_ebitda',
        name: 'EV/EBITDA',
        description: '企业价值与息税折旧摊销前利润的比值',
        source: '研究机构',
        useCase: '消除财务结构和税收影响，更客观',
        category: 'micro',
        subcategory: '估值指标',
      },
      {
        id: 'dividend_yield',
        name: '股息率',
        description: '年度分红与股价的比值',
        source: '交易所',
        useCase: '股息率高→分红收益好；低→增长潜力大',
        category: 'micro',
        subcategory: '估值指标',
      },
    ],
    safety: [
      {
        id: 'debt_ratio',
        name: '资产负债率',
        description: '负债与资产的比值',
        source: '财务报表',
        useCase: '<50%→安全；>70%→风险高',
        category: 'micro',
        subcategory: '财务安全',
      },
      {
        id: 'current_ratio',
        name: '流动比率',
        description: '流动资产与流动负债的比值',
        source: '财务报表',
        useCase: '>1.5→流动性充足；<1→风险信号',
        category: 'micro',
        subcategory: '财务安全',
      },
      {
        id: 'quick_ratio',
        name: '速动比率',
        description: '（流动资产-存货）与流动负债的比值',
        source: '财务报表',
        useCase: '>1→短期偿债能力强',
        category: 'micro',
        subcategory: '财务安全',
      },
      {
        id: 'interest_coverage',
        name: '利息覆盖倍数',
        description: 'EBIT与利息支出的比值',
        source: '财务报表',
        useCase: '>3→能够轻松支付利息；<1.5→风险高',
        category: 'micro',
        subcategory: '财务安全',
      },
      {
        id: 'debt_ebitda',
        name: '债务/EBITDA',
        description: '总债务与息税折旧摊销前利润的比值',
        source: '财务报表',
        useCase: '<3→债务水平合理；>5→债务过高',
        category: 'micro',
        subcategory: '财务安全',
      },
    ],
    technical: [
      {
        id: 'ma',
        name: 'MA（移动平均线）',
        description: '一定时期内的平均价格',
        source: 'K线图',
        useCase: '金叉（短期MA>长期MA）→买入信号；死叉→卖出信号',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'macd',
        name: 'MACD（指数平滑异同移动平均线）',
        description: '快线与慢线的差值',
        source: 'K线图',
        useCase: 'MACD>0且向上→上升趋势；<0且向下→下降趋势',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'rsi',
        name: 'RSI（相对强弱指数）',
        description: '衡量上升和下降力度的指标',
        source: 'K线图',
        useCase: 'RSI>70→超买（可能回调）；<30→超卖（可能反弹）',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'kdj',
        name: 'KDJ指数',
        description: '随机指标，衡量价格动量',
        source: 'K线图',
        useCase: 'K>80→超买；K<20→超卖',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'boll',
        name: 'BOLL（布林带）',
        description: '由中线、上轨、下轨组成的通道',
        source: 'K线图',
        useCase: '价格触及上轨→可能回调；触及下轨→可能反弹',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'volume',
        name: '成交量（VOL）',
        description: '股票交易的数量',
        source: 'K线图',
        useCase: '价格上升伴随成交量增加→趋势可靠；无量上升→虚弱',
        category: 'micro',
        subcategory: '技术面',
      },
      {
        id: 'turnover_stock',
        name: '换手率',
        description: '成交量与流通股本的比例',
        source: '交易所',
        useCase: '换手率高→短期炒作；低→缺乏关注',
        category: 'micro',
        subcategory: '技术面',
      },
    ],
    chip: [
      {
        id: 'shareholder',
        name: '股东人数变化',
        description: '上市公司股东总数的变化趋势',
        source: '定期公告',
        useCase: '股东人数下降→筹码集中，可能上升；上升→筹码分散',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
      {
        id: 'institution_holding',
        name: '机构持股比例',
        description: '基金、保险等机构投资者的持股比例',
        source: '定期公告',
        useCase: '机构持股比例高→机构看好；下降→减仓信号',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
      {
        id: 'fund_holding_stock',
        name: '基金持仓变化',
        description: '公募基金对该股的持仓数量变化',
        source: '基金定期报告',
        useCase: '持仓增加→机构看好；持仓减少→机构看空',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
      {
        id: 'dragon_tiger',
        name: '龙虎榜数据',
        description: '日成交额排名前5的游资和机构的买卖动向',
        source: '交易所',
        useCase: '游资持续买入→短期炒作；机构买入→长期看好',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
      {
        id: 'block_trade',
        name: '大宗交易',
        description: '单笔成交金额超过500万元的交易',
        source: '交易所',
        useCase: '大宗交易溢价→看好；折价→看空',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
      {
        id: 'margin_stock',
        name: '融资余额占流通市值比',
        description: '融资融券与流通市值的比例',
        source: '交易所',
        useCase: '比例过高→杠杆过高，风险大',
        category: 'micro',
        subcategory: '筹码与情绪',
      },
    ],
  },
};

export const CATEGORIES = {
  macro: {
    title: '国家股票整体（宏观/大盘）',
    description: '分析整体市场走势，主要关注宏观经济、政策环境和流动性',
    subcategories: [
      { key: '宏观经济', color: '#0066cc' },
      { key: '流动性与货币政策', color: '#00a3ff' },
      { key: '政策与预期', color: '#0052a3' },
      { key: '市场估值与情绪', color: '#003d7a' },
    ],
  },
  meso: {
    title: '具体股票板块（中观/行业）',
    description: '分析行业轮动和板块强度，关注景气度和估值',
    subcategories: [
      { key: '行业景气度', color: '#ff6b35' },
      { key: '板块估值', color: '#f7931e' },
      { key: '资金与情绪', color: '#fdb833' },
      { key: '外部催化', color: '#f37021' },
    ],
  },
  micro: {
    title: '具体个股（微观）',
    description: '分析单只股票的投资价值，结合基本面和技术面',
    subcategories: [
      { key: '基本面（财务）', color: '#2ecc71' },
      { key: '估值指标', color: '#27ae60' },
      { key: '财务安全', color: '#229954' },
      { key: '技术面', color: '#9b59b6' },
      { key: '筹码与情绪', color: '#8e44ad' },
    ],
  },
};
