-- 经济日历事件表
CREATE TABLE public.economic_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    country TEXT NOT NULL,
    title TEXT NOT NULL,
    impact TEXT NOT NULL, -- High, Medium, Low
    actual TEXT,
    forecast TEXT,
    previous TEXT,
    source TEXT NOT NULL DEFAULT 'Forex Factory',
    collected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_event UNIQUE (event_id, event_timestamp)
);

COMMENT ON TABLE public.economic_events IS 'Forex Factory 经济日历事件';
COMMENT ON COLUMN public.economic_events.event_id IS '事件唯一标识符，从URL中提取';
COMMENT ON COLUMN public.economic_events.event_timestamp IS '事件发生时间';
COMMENT ON COLUMN public.economic_events.country IS '相关国家/货币';
COMMENT ON COLUMN public.economic_events.title IS '事件标题';
COMMENT ON COLUMN public.economic_events.impact IS '重要性等级';
COMMENT ON COLUMN public.economic_events.actual IS '实际值';
COMMENT ON COLUMN public.economic_events.forecast IS '预测值';
COMMENT ON COLUMN public.economic_events.previous IS '前值';

CREATE INDEX idx_economic_events_timestamp ON public.economic_events (event_timestamp DESC);
CREATE INDEX idx_economic_events_country ON public.economic_events (country);
CREATE INDEX idx_economic_events_impact ON public.economic_events (impact);
